package com.infosoft.sira.geografia;
import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/v1/geografia") public class GeografiaController{private final JdbcTemplate db;public GeografiaController(JdbcTemplate db){this.db=db;}
@GetMapping("/paises") public List<Map<String,Object>> paises(){return db.queryForList("select id_pais,codigo_iso2,desc_pais from sira.pais where activo='S' order by case when codigo_iso2='VE' then 0 else 1 end,desc_pais");}
@GetMapping("/estados") public List<Map<String,Object>> estados(@RequestParam long paisId){return db.queryForList("select id_estado,desc_estado from sira.estado where activo='S' and id_pais=? order by desc_estado",paisId);}
@GetMapping("/ciudades") public List<Map<String,Object>> ciudades(@RequestParam long estadoId){return db.queryForList("select id_ciudad,desc_ciudad from sira.ciudad where activo='S' and id_estado=? order by desc_ciudad",estadoId);}
@GetMapping("/municipios") public List<Map<String,Object>> municipios(@RequestParam(required=false) Long ciudadId,@RequestParam(required=false) Long estadoId){return ciudadId!=null?db.queryForList("select id_municipio,desc_municipio from sira.municipio where activo='S' and id_ciudad=? order by desc_municipio",ciudadId):db.queryForList("select distinct m.id_municipio,m.desc_municipio from sira.municipio m left join sira.ciudad c on c.id_ciudad=m.id_ciudad where m.activo='S' and c.id_estado=? order by m.desc_municipio",estadoId);}
@GetMapping("/parroquias") public List<Map<String,Object>> parroquias(@RequestParam long municipioId){return db.queryForList("select id_parroquia,desc_parroquia from sira.parroquia where activo='S' and id_municipio=? order by desc_parroquia",municipioId);}
@GetMapping("/tipos-sector") public List<Map<String,Object>> tipos(){return db.queryForList("select id_tipo_sector_geografico,desc_tipo_sector_geografico from sira.tipo_sector_geografico where activo='S' order by desc_tipo_sector_geografico");}
@GetMapping("/sectores") public List<Map<String,Object>> sectores(@RequestParam long estadoId,@RequestParam(required=false) Long ciudadId,@RequestParam(required=false) Long municipioId,@RequestParam(required=false) Long parroquiaId,@RequestParam(required=false) Long tipoSectorId){return db.queryForList("select id_sector_geografico,id_tipo_sector_geografico,desc_sector_geografico from sira.sector_geografico where activo='S' and id_estado=? and (? is null or id_tipo_sector_geografico=?) and ((? is not null and id_parroquia=?) or (id_parroquia is null and ? is not null and id_municipio=?) or (id_parroquia is null and id_municipio is null and ? is not null and id_ciudad=?) or (id_parroquia is null and id_municipio is null and id_ciudad is null)) order by desc_sector_geografico",estadoId,tipoSectorId,tipoSectorId,parroquiaId,parroquiaId,municipioId,municipioId,ciudadId,ciudadId);}
@GetMapping("/codigos-postales") public List<Map<String,Object>> cp(@RequestParam long sectorId){return db.queryForList("select id_codigo_postal,codigo_postal from sira.codigo_postal where activo='S' and id_sector_geografico=? order by codigo_postal",sectorId);}
@GetMapping("/codigos-telefonicos") public List<Map<String,Object>> codigos(){return db.queryForList("select id_codigo_telefonico,codigo_pais,codigo_area_operador,descripcion,tipo_linea from sira.cat_codigo_telefonico where activo='S' order by tipo_linea,codigo_area_operador");}
@GetMapping("/tipos-contacto") public List<Map<String,Object>> contactos(){return db.queryForList("select id_tipo_contacto,codigo,descripcion,permite_otp from sira.cat_tipo_contacto where activo='S' order by id_tipo_contacto");}}
