package com.infosoft.sira.invitacion;

import com.infosoft.sira.electoral.ElectoralController;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;
import java.util.*;

@RestController
@RequestMapping("/api/v1/publico/invitaciones")
public class PublicInvitacionController {
 private final InvitacionController service; private final JdbcTemplate db; private final ElectoralController electoral;
 public PublicInvitacionController(InvitacionController service,JdbcTemplate db,ElectoralController electoral){this.service=service;this.db=db;this.electoral=electoral;}
 @PostMapping("/validar") public Map<String,Object> validar(@RequestBody Map<String,Object> p){return service.validar(p);}

 @GetMapping("/codigos-telefonicos") public List<Map<String,Object>> codigos(){return db.queryForList("select id_codigo_telefonico,codigo_pais,codigo_area_operador,descripcion,tipo_linea from sira.cat_codigo_telefonico where activo='S' order by tipo_linea,codigo_area_operador");}
 @GetMapping("/tipos-contacto") public List<Map<String,Object>> tipos(){return db.queryForList("select id_tipo_contacto,codigo,descripcion,permite_otp from sira.cat_tipo_contacto where activo='S' order by id_tipo_contacto");}
 @GetMapping("/catalogos/nacionalidades") public List<Map<String,Object>> nacionalidades(){return db.queryForList("select id_nacionalidad_catalogo,descripcion from sira.cat_nacionalidad where activo='S' order by descripcion");}
 @GetMapping("/catalogos/sexos") public List<Map<String,Object>> sexos(){return db.queryForList("select id_sexo,descripcion from sira.cat_sexo where activo='S' order by descripcion");}
 @GetMapping("/catalogos/honores") public List<Map<String,Object>> honores(){return db.queryForList("select id_honor,descripcion from sira.cat_honor_academico where activo='S' order by descripcion");}
 @GetMapping("/catalogos/disponibilidades") public List<Map<String,Object>> disponibilidades(){return db.queryForList("select id_disponibilidad,descripcion from sira.cat_disponibilidad where activo='S' order by descripcion");}
 @GetMapping("/catalogos/niveles") public List<Map<String,Object>> niveles(){return db.queryForList("select id_nivel,descripcion from sira.cat_nivel_educativo where activo='S' order by descripcion");}
 @GetMapping("/catalogos/especialidades") public List<Map<String,Object>> especialidades(){return db.queryForList("select id_especialidad,descripcion from sira.cat_especialidad where activo='S' order by descripcion");}
 @GetMapping("/catalogos/modalidades") public List<Map<String,Object>> modalidades(){return db.queryForList("select id_modalidad,descripcion from sira.cat_modalidad where activo='S' order by descripcion");}
 @GetMapping("/geografia/paises") public List<Map<String,Object>> paises(){return db.queryForList("select id_pais,desc_pais from sira.pais where activo='S' order by desc_pais");}
 @GetMapping("/geografia/estados") public List<Map<String,Object>> estados(@RequestParam long paisId){return db.queryForList("select id_estado,desc_estado from sira.estado where activo='S' and id_pais=? order by desc_estado",paisId);}
 @GetMapping("/geografia/ciudades") public List<Map<String,Object>> ciudades(@RequestParam long estadoId){return db.queryForList("select id_ciudad,desc_ciudad from sira.ciudad where activo='S' and id_estado=? order by desc_ciudad",estadoId);}
 @GetMapping("/geografia/municipios") public List<Map<String,Object>> municipios(@RequestParam long ciudadId){return db.queryForList("select id_municipio,desc_municipio from sira.municipio where activo='S' and id_ciudad=? order by desc_municipio",ciudadId);}
 @GetMapping("/geografia/parroquias") public List<Map<String,Object>> parroquias(@RequestParam long municipioId){return db.queryForList("select id_parroquia,desc_parroquia from sira.parroquia where activo='S' and id_municipio=? order by desc_parroquia",municipioId);}
 @GetMapping("/geografia/tipos-sector") public List<Map<String,Object>> tiposSector(){return db.queryForList("select id_tipo_sector_geografico,desc_tipo_sector_geografico from sira.tipo_sector_geografico where activo='S' order by desc_tipo_sector_geografico");}
 @GetMapping("/geografia/sectores") public List<Map<String,Object>> sectores(@RequestParam(required=false) Long estadoId,@RequestParam(required=false) Long ciudadId,@RequestParam(required=false) Long municipioId,@RequestParam(required=false) Long parroquiaId,@RequestParam long tipoSectorId){return db.queryForList("select id_sector_geografico,desc_sector_geografico from sira.sector_geografico where activo='S' and id_tipo_sector_geografico=? and (? is null or id_estado=?) and (? is null or id_ciudad=?) and (? is null or id_municipio=?) and (? is null or id_parroquia=?) order by desc_sector_geografico",tipoSectorId,estadoId,estadoId,ciudadId,ciudadId,municipioId,municipioId,parroquiaId,parroquiaId);}
 @GetMapping("/geografia/codigos-postales") public List<Map<String,Object>> postales(@RequestParam long sectorId){return db.queryForList("select id_codigo_postal,codigo_postal from sira.codigo_postal where activo='S' and id_sector_geografico=? order by codigo_postal",sectorId);}

 @PostMapping("/iniciar") @Transactional
 public Map<String,Object> iniciar(@RequestBody Map<String,Object> p){
  String token=text(p.get("token"));Map<String,Object> inv=service.validar(Map.of("token",token));long iid=num(inv.get("id_invitacion"));
  Map<String,Object> row=db.queryForMap("select *,to_jsonb(i) datos from sira.inv_invitacion i where id_invitacion=?",iid);
  boolean abierta="S".equals(row.get("es_abierta"));String doc=digits(p.get("documentoNumero"));if(doc.length()<5)bad("Documento inválido");
  long pais=num(p.getOrDefault("paisEmisorId",1));long tipo=num(p.getOrDefault("tipoDocumentoId",1));long nac=num(p.getOrDefault("nacionalidadCatalogoId",1));
  var found=db.queryForList("select id_persona from sira.per_persona where id_pais_emisor=? and id_tipo_documento=? and documento_numero=? limit 1",pais,tipo,doc);
  boolean existente=!found.isEmpty();long pid;
  if(existente)pid=((Number)found.get(0).get("id_persona")).longValue();
  else pid=db.queryForObject("insert into sira.per_persona(id_pais_emisor,id_tipo_documento,documento_numero,id_nacionalidad_catalogo,id_referido,consentimiento_datos,estado_registro) values(?,?,?,?,?,'S','ACTIVO') returning id_persona",Long.class,pais,tipo,doc,nac,row.get("id_referido"));
  if(!abierta){Object amarrada=row.get("id_persona_resultante");if(amarrada!=null&&num(amarrada)!=pid)throw new ResponseStatusException(HttpStatus.CONFLICT,"La invitación dirigida corresponde a otra persona");db.update("update sira.inv_invitacion set id_persona_resultante=? where id_invitacion=?",pid,iid);}
  long uso=db.queryForObject("insert into sira.inv_invitacion_persona(id_invitacion,id_persona,persona_existente,otp_pendiente) values(?,?,?,?) on conflict(id_invitacion,id_persona) do update set fecha_ultimo_acceso=clock_timestamp() returning id_invitacion_persona",Long.class,iid,pid,existente?"S":"N",existente?"S":"N");
  guardarContacto(pid,p);Map<String,Object> cne;try{cne=electoral.consultar(pid,Map.of("nacionalidad","V"));}catch(Exception e){cne=Map.of("errorProveedor",String.valueOf(e.getMessage()));}
  Map<String,Object> out=new LinkedHashMap<>();out.put("personaId",pid);out.put("usoId",uso);out.put("personaExistente",existente);out.put("otpPendiente",existente);out.put("invitacionAbierta",abierta);out.put("electoral",cne);return out;
 }

 @GetMapping("/{token}/contexto") public Map<String,Object> contexto(@PathVariable String token,@RequestParam long usoId){long pid=personaUso(token,usoId);Map<String,Object> o=new LinkedHashMap<>();o.put("persona",db.queryForMap("select * from sira.per_persona where id_persona=?",pid));o.put("contactos",contactos(pid));o.put("residencia",one("select * from sira.per_persona_residencia where id_persona=? and activo='S' and principal='S' limit 1",pid));o.put("academico",one("select * from sira.per_persona_datos_academicos where id_persona=?",pid));o.put("electoral",electoral.actual(pid));o.put("grupos",db.queryForList("select g.id_grupo,g.descripcion from sira.per_persona_grupo pg join sira.org_grupo g on g.id_grupo=pg.id_grupo where pg.id_persona=? and pg.activo='S'",pid));o.put("catalogoGrupos",db.queryForList("select id_grupo,descripcion from sira.org_grupo where activo='S' order by descripcion"));return o;}
 @PutMapping("/{token}/personales") public Map<String,Object> personales(@PathVariable String token,@RequestParam long usoId,@RequestBody Map<String,Object>x){long pid=personaUso(token,usoId);db.update("update sira.per_persona set primer_nombre=?,segundo_nombre=?,primer_apellido=?,segundo_apellido=?,alias_apodo=?,fecha_nacimiento=nullif(?,'')::date,id_nacionalidad_catalogo=?,id_sexo=? where id_persona=?",up(x.get("primerNombre")),up(x.get("segundoNombre")),up(x.get("primerApellido")),up(x.get("segundoApellido")),text(x.get("aliasApodo")),text(x.get("fechaNacimiento")),nullable(x.get("nacionalidadCatalogoId")),nullable(x.get("sexoId")),pid);return ok();}
 @PostMapping("/{token}/correo") public Map<String,Object> correo(@PathVariable String token,@RequestParam long usoId,@RequestBody Map<String,Object>x){long pid=personaUso(token,usoId);String c=text(x.get("correo")).toLowerCase();db.update("update sira.per_persona_correo set principal='N' where id_persona=? and principal='S'",pid);db.update("insert into sira.per_persona_correo(id_persona,correo,principal,verificado,activo) values(?,?,'S','N','S') on conflict do nothing",pid,c);return ok();}
 @PostMapping("/{token}/telefono") public Map<String,Object> telefono(@PathVariable String token,@RequestParam long usoId,@RequestBody Map<String,Object>x){long pid=personaUso(token,usoId);String n=digits(x.get("numero"));if(n.length()!=7)bad("El teléfono debe tener 7 dígitos");db.update("update sira.per_persona_telefono set principal='N' where id_persona=? and principal='S'",pid);db.update("insert into sira.per_persona_telefono(id_persona,id_tipo_contacto,id_codigo_telefonico,numero,extension,principal,usa_whatsapp,verificado,activo) select ?,?,?,?,?, 'S',?,'N','S' where not exists(select 1 from sira.per_persona_telefono where id_persona=? and id_codigo_telefonico=? and numero=? and activo='S')",pid,num(x.get("tipoContactoId")),num(x.get("codigoTelefonicoId")),n,text(x.get("extension")),Boolean.TRUE.equals(x.get("usaWhatsapp"))?"S":"N",pid,num(x.get("codigoTelefonicoId")),n);return ok();}
 @PutMapping("/{token}/territorio") public Map<String,Object> territorio(@PathVariable String token,@RequestParam long usoId,@RequestBody Map<String,Object>x){long pid=personaUso(token,usoId);Long pais=nullable(x.get("paisId"));if(pais==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"El país es obligatorio");db.update("update sira.per_persona_residencia set activo='N',principal='N',fecha_hasta=current_date where id_persona=? and activo='S'",pid);db.update("insert into sira.per_persona_residencia(id_persona,id_pais,id_estado,id_ciudad,id_municipio,id_parroquia,id_sector_geografico,id_codigo_postal,direccion_complementaria,principal,activo) values(?,?,?,?,?,?,?,?,?,'S','S')",pid,pais,nullable(x.get("estadoId")),nullable(x.get("ciudadId")),nullable(x.get("municipioId")),nullable(x.get("parroquiaId")),nullable(x.get("sectorId")),nullable(x.get("codigoPostalId")),text(x.get("direccionComplementaria")));return ok();}
 @PutMapping("/{token}/academico") public Map<String,Object> academico(@PathVariable String token,@RequestParam long usoId,@RequestBody Map<String,Object>x){long pid=personaUso(token,usoId);db.update("insert into sira.per_persona_datos_academicos(id_persona,id_nivel,id_especialidad,titulo,postgrado,descripcion_postgrado,doctorado,descripcion_doctorado,magister,descripcion_magister,id_honor,ocupacion_1,ocupacion_2,ocupacion_3,id_disponibilidad,id_modalidad,whatsapp,facebook,instagram,youtube,x_twitter,observacion,fecha_actualizacion,usuario_actualizacion,titulo_2,id_especialidad_2) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,clock_timestamp(),'PUBLICO_INVITACION',?,?) on conflict(id_persona) do update set id_nivel=excluded.id_nivel,id_especialidad=excluded.id_especialidad,titulo=excluded.titulo,postgrado=excluded.postgrado,descripcion_postgrado=excluded.descripcion_postgrado,doctorado=excluded.doctorado,descripcion_doctorado=excluded.descripcion_doctorado,magister=excluded.magister,descripcion_magister=excluded.descripcion_magister,id_honor=excluded.id_honor,ocupacion_1=excluded.ocupacion_1,ocupacion_2=excluded.ocupacion_2,ocupacion_3=excluded.ocupacion_3,id_disponibilidad=excluded.id_disponibilidad,id_modalidad=excluded.id_modalidad,whatsapp=excluded.whatsapp,facebook=excluded.facebook,instagram=excluded.instagram,youtube=excluded.youtube,x_twitter=excluded.x_twitter,observacion=excluded.observacion,fecha_actualizacion=clock_timestamp(),usuario_actualizacion='PUBLICO_INVITACION',titulo_2=excluded.titulo_2,id_especialidad_2=excluded.id_especialidad_2",pid,nullable(x.get("nivelId")),nullable(x.get("especialidadId")),text(x.get("titulo")),yn(x.get("postgrado")),text(x.get("descripcionPostgrado")),yn(x.get("doctorado")),text(x.get("descripcionDoctorado")),yn(x.get("magister")),text(x.get("descripcionMagister")),nullable(x.get("honorId")),text(x.get("ocupacion1")),text(x.get("ocupacion2")),text(x.get("ocupacion3")),nullable(x.get("disponibilidadId")),nullable(x.get("modalidadId")),text(x.get("whatsapp")),text(x.get("facebook")),text(x.get("instagram")),text(x.get("youtube")),text(x.get("xTwitter")),text(x.get("observacion")),text(x.get("titulo2")),nullable(x.get("especialidad2Id")));return ok();}
 @PostMapping("/{token}/grupos/{gid}") public Map<String,Object> grupo(@PathVariable String token,@RequestParam long usoId,@PathVariable long gid){long pid=personaUso(token,usoId);db.update("insert into sira.per_persona_grupo(id_persona,id_grupo) values(?,?) on conflict(id_persona,id_grupo) do update set activo='S',fecha_hasta=null",pid,gid);return ok();}
 @DeleteMapping("/{token}/grupos/{gid}") public Map<String,Object> quitar(@PathVariable String token,@RequestParam long usoId,@PathVariable long gid){long pid=personaUso(token,usoId);db.update("update sira.per_persona_grupo set activo='N',fecha_hasta=clock_timestamp() where id_persona=? and id_grupo=?",pid,gid);return ok();}
 @PostMapping("/{token}/finalizar") public Map<String,Object> finalizar(@PathVariable String token,@RequestParam long usoId){long pid=personaUso(token,usoId);db.update("update sira.inv_invitacion_persona set estado='REGISTRADO',fecha_finalizacion=clock_timestamp() where id_invitacion_persona=?",usoId);Integer ok=db.queryForObject("select case when p.primer_nombre is not null and p.primer_apellido is not null and exists(select 1 from sira.per_persona_telefono t where t.id_persona=p.id_persona and t.activo='S') and exists(select 1 from sira.per_persona_correo c where c.id_persona=p.id_persona and c.activo='S') then 1 else 0 end from sira.per_persona p where p.id_persona=?",Integer.class,pid);if(ok!=null&&ok==1)db.update("update sira.per_persona set registro_fase1_completo='S' where id_persona=?",pid);return Map.of("finalizado",true,"fase1Completa",ok!=null&&ok==1);}


 private long personaUso(String token,long uso){Map<String,Object> inv=service.validar(Map.of("token",token));var r=db.queryForList("select ip.id_persona from sira.inv_invitacion_persona ip where ip.id_invitacion_persona=? and ip.id_invitacion=? and ip.estado in ('ABIERTO','REGISTRADO')",uso,inv.get("id_invitacion"));if(r.isEmpty())throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Registro de invitación no válido");db.update("update sira.inv_invitacion_persona set fecha_ultimo_acceso=clock_timestamp() where id_invitacion_persona=?",uso);return num(r.get(0).get("id_persona"));}
 private void guardarContacto(long pid,Map<String,Object>p){Object c=p.get("codigoTelefonicoId");String n=digits(p.get("numero")),m=text(p.get("correo"));if(c!=null&&!n.isBlank()){Long t=db.queryForObject("select id_tipo_contacto from sira.cat_tipo_contacto where activo='S' order by case when upper(codigo) like 'CELULAR%' then 0 else 1 end,id_tipo_contacto limit 1",Long.class);db.update("insert into sira.per_persona_telefono(id_persona,id_tipo_contacto,id_codigo_telefonico,numero,principal,usa_whatsapp,verificado,activo) select ?,?,?,?,'S','S','N','S' where not exists(select 1 from sira.per_persona_telefono where id_persona=? and id_codigo_telefonico=? and numero=? and activo='S')",pid,t,num(c),n,pid,num(c),n);}if(m!=null&&!m.isBlank())db.update("insert into sira.per_persona_correo(id_persona,correo,principal,verificado,activo) select ?,lower(?),'S','N','S' where not exists(select 1 from sira.per_persona_correo where id_persona=? and lower(correo)=lower(?) and activo='S')",pid,m,pid,m);}
 private Map<String,Object> contactos(long p){Map<String,Object>x=new LinkedHashMap<>();x.put("correos",db.queryForList("select * from sira.per_persona_correo where id_persona=? and activo='S'",p));x.put("telefonos",db.queryForList("select t.*,c.codigo_pais,c.codigo_area_operador from sira.per_persona_telefono t join sira.cat_codigo_telefonico c on c.id_codigo_telefonico=t.id_codigo_telefonico where t.id_persona=? and t.activo='S'",p));return x;}
 private Map<String,Object> one(String q,long p){var r=db.queryForList(q,p);return r.isEmpty()?Map.of():r.get(0);}private Map<String,Object> ok(){return Map.of("guardado",true);}private void bad(String x){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,x);}private long num(Object x){return Long.parseLong(String.valueOf(x));}private Long nullable(Object x){try{String s=String.valueOf(x);return s.isBlank()||"None".equals(s)?null:Long.valueOf(s);}catch(Exception e){return null;}}private String text(Object x){return x==null?"":String.valueOf(x).trim();}private String digits(Object x){return text(x).replaceAll("\\D","");}private String up(Object x){String s=text(x);return s.isBlank()?null:s.toUpperCase();}private String yn(Object x){return Boolean.TRUE.equals(x)?"S":"N";}
}
