package com.infosoft.sira.academico;
import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/v1/personas/{personaId}/academico") public class AcademicoController{private final JdbcTemplate db;public AcademicoController(JdbcTemplate db){this.db=db;}
@GetMapping public Map<String,Object> get(@PathVariable long personaId){var r=db.queryForList("select * from sira.per_persona_datos_academicos where id_persona=?",personaId);return r.isEmpty()?Map.of():r.get(0);}
@PutMapping @Transactional public Map<String,Object> put(@PathVariable long personaId,@RequestBody Map<String,Object> p){db.update("""
insert into sira.per_persona_datos_academicos(id_persona,id_nivel,id_titulo_1,id_especialidad,id_titulo_2,id_especialidad_2,postgrado,descripcion_postgrado,doctorado,descripcion_doctorado,magister,descripcion_magister,id_honor,ocupacion_1,ocupacion_2,ocupacion_3,id_disponibilidad,id_modalidad,observacion)
values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) on conflict(id_persona) do update set id_nivel=excluded.id_nivel,id_titulo_1=excluded.id_titulo_1,id_especialidad=excluded.id_especialidad,id_titulo_2=excluded.id_titulo_2,id_especialidad_2=excluded.id_especialidad_2,postgrado=excluded.postgrado,descripcion_postgrado=excluded.descripcion_postgrado,doctorado=excluded.doctorado,descripcion_doctorado=excluded.descripcion_doctorado,magister=excluded.magister,descripcion_magister=excluded.descripcion_magister,id_honor=excluded.id_honor,ocupacion_1=excluded.ocupacion_1,ocupacion_2=excluded.ocupacion_2,ocupacion_3=excluded.ocupacion_3,id_disponibilidad=excluded.id_disponibilidad,id_modalidad=excluded.id_modalidad,observacion=excluded.observacion,fecha_actualizacion=clock_timestamp(),usuario_actualizacion=current_user
""",personaId,n(p.get("nivelId")),n(p.get("titulo1Id")),n(p.get("especialidadId")),n(p.get("titulo2Id")),n(p.get("especialidad2Id")),b(p.get("postgrado")),t(p.get("descripcionPostgrado")),b(p.get("doctorado")),t(p.get("descripcionDoctorado")),b(p.get("magister")),t(p.get("descripcionMagister")),n(p.get("honorId")),t(p.get("ocupacion1")),t(p.get("ocupacion2")),t(p.get("ocupacion3")),n(p.get("disponibilidadId")),n(p.get("modalidadId")),t(p.get("observacion")));return Map.of("guardado",true);}
private Long n(Object v){return v==null||String.valueOf(v).isBlank()?null:Long.valueOf(String.valueOf(v));}private String t(Object v){return v==null?null:String.valueOf(v).trim();}private String b(Object v){return Boolean.TRUE.equals(v)||"true".equalsIgnoreCase(String.valueOf(v))?"S":"N";}}
